### PR TITLE
Fixes issues with newer versions of PHP using the same parameter name…

### PR DESCRIPTION
**Pull request by VBGAMER45**
Fixes issues with newer versions of PHP using the same parameter name in function call.

### CODE REVIEW

**Comment by VBGAMER45** [comment]
Also if you can update the MOD on simplemachines.org with the fix that would be awesome.

**Comment by xchwarze** [comment]
Thanks @VBGAMER45 !
As far as I remember never finished plugin validation at simplemachines.org
So there shouldn't be any uploaded version there

**Comment by VBGAMER45** [comment]
Hmm, yeah I guess, I can see it as I am on staff there. You can try to resubmit. The last issue I see was missing the license text. File just a copy of GPL in a text file license

**Comment by xchwarze** [comment]
Actually the reason why the validation did not finish was because it took too looooong.
Anyway I am no longer interested in validating it.

**Comment by VBGAMER45** [comment]
Would you mind if I submit it but state your name as a Author? and include link back to github etc.

Yes, I agree with the polices of mod approval take too long as an author that makes people not want to contribute.

**Comment by xchwarze** [comment]
I have no problem with that

**Pull request merged**
